### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by PetrVladimirov** [aakatov/anki-media-internalizer#4]
Window after the execution (1 note with http image):
![image](https://user-images.githubusercontent.com/35421649/34915645-dc5a6320-f93a-11e7-9426-bc118280da8a.png)

Actually it is still http ref. in the note:
![image](https://user-images.githubusercontent.com/35421649/34915664-3b493118-f93b-11e7-8805-c71f50e020ed.png)

Anki version:
![image](https://user-images.githubusercontent.com/35421649/34915671-5442a168-f93b-11e7-885d-21334756aceb.png)

It would be great if you fix!

**Comment by aakatov** [comment]
Hi! Could you please export and upload your deck so I can reproduce it? I tried on my deck and it worked fine.

**Comment by aakatov** [comment]
Ok, I found the bug. Please, update the plugin and let me know whether the problem persists. Thanks.

**Comment by PetrVladimirov** [comment]
Many thanks!
