### ISSUE TITLE
Reference with double URL entry produces an error

### ISSUE THREAD

**Issue by PetrVladimirov** [aakatov/anki-media-internalizer#5]
It is probably not the often case, but when having an image reference with two URLs within, it is not processed by media-internalizer (e.g. when you use duckduckgo search engine). It would be great to have it fixed somehow.

Example:
`<img src="https://images.duckduckgo.com/iu/?u=http%3A%2F%2Fwww.marekrei.com%2Fblog%2Fwp-content%2Fuploads%2F2015%2F08%2F2015_DLSS_ConvexOptimization.png&amp;f=1"`

![image](https://user-images.githubusercontent.com/35421649/35184044-4d37601e-fe01-11e7-91cd-b6ded3ce6c24.png)

**Comment by aakatov** [comment]
Fixed. Please, update the plugin. Thanks for reporting.
