### ISSUE TITLE
Feature request: reduce the resolution of an image to a smaller predefined one

### ISSUE THREAD

**Issue by PetrVladimirov** [aakatov/anki-media-internalizer#6]
It would be great to to have size of the image reduced to a smaller one while its "internalized".

Use case: modern images in the Internet tend to be too large for Anki's purposes. Many times they take too much size of the screen during repetition and consume additional amount of space.

It should have at least several basic settings:
- whether to reduce images or keep original size. If reduce then:
  - max resolution for final (internalized) images
  - whether to leave proportion of images. If yes is chosen, then:
    - a primarily axe to use while reducing

Ideally, it should not use any external service, so no additional dependencies are created.

**Comment by aakatov** [comment]
This sounds like an idea for another addon that would process images that are already in the storage. Perhaphs there is already one. 
I want to keep Media Internalizer clean and simple with single responsibility - eliminating external references.
